# base on ubuntu:20.04+ only
ARG base_image=ubuntu:22.04
FROM ${base_image}

LABEL maintainer="nikshuang@sina.com"

# Install dependent packages
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    wget \
    vim \
    python3 \
    python3-pip \
    librdmacm-dev \
    ssh \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
RUN chmod +x Miniconda3-latest-Linux-x86_64.sh
RUN ./Miniconda3-latest-Linux-x86_64.sh -b
RUN echo "PATH=/root/miniconda3/bin:$PATH" >> ~/.bashrc

RUN ln -s /usr/bin/python3 /usr/bin/python

WORKDIR /root
COPY examples examples

